# Author: Rourke750
# Bukkit Page located here: http://dev.bukkit.org/bukkit-plugins/expensive-beacons/
# Github located here: https://github.com/rourke750/Expensive-Beacon
# 
# apply_effects: This says how long effects will last on a player. (ticks)
# effects_applied: This determines how long the plugin waits to check if a player is within range to give them an effect. (ticks)
# save: How long before each save. (ticks)
# beacon_speed: Parent for defining speed beacon tiers.
# 		tier_1: Tier 1 of the Speed Beacon.
# 			range: The range that the tier 1 speed beacon checks.
# 		tier_2: Tier 2 of the Speed Beacon.
# 			range: The range that the tier 1 speed beacon checks.
# 		tier_3: Tier 3 of the Speed Beacon.
# 			range: The range that the tier 1 speed beacon checks.
# 		tier_4: Tier 4 of the Speed Beacon.
# 			range: The range that the tier 1 speed beacon checks.
#  	tier_5: Tier 5 of the Speed Beacon.
# 			range: The range that the tier 1 speed beacon checks.
# maturation_time: The amount of time for a beacon to become active, in minutes.
# beacon_hitpoints: The amount of breaks it takes to destroy the entire structure. 356210 is about the time of 20 layers of dro.
# beacon_death_invulnerability: The amount of time the beacon stays invulnerable after it's hitpoints reach zero.
# beacon_repair_time: The amount of time it takes to run the repair method. In ticks.
# beacon_force_repair_id: The item id which should be required when repairing.
# beacon_force_repair_cost: The cost it takes to repair a beacon when it is broken.

apply_effects: 1200
effects_applied: 100
save: 24000
beacon_speed:
  tier_1:
    range: 30
  tier_2:
    range: 55
  tier_3:
    range: 72
  tier_4:
    range: 80
  tier_5:
    range: 100
beacon_strength:
  tier_1:
    range: 25
  tier_2:
    range: 47
  tier_3:
    range: 68
  tier_4:
    range: 80
  tier_5:
    range: 105
beacon_regen:
  tier_1:
    range: 25
  tier_2:
    range: 50
  tier_3:
    range: 65
  tier_4:
    range: 85
  tier_5:
    range: 100
beacon_haste:
  tier_1:
    range: 35
  tier_2:
    range: 60
  tier_3:
    range: 80
  tier_4:
    range: 100
  tier_5:
    range: 120
beacon_super:
  range: 300
maturation_time: 1440
beacon_hitpoints: 356210
beacon_death_invulnerability: 1440
beacon_repair_time: 72000
beacon_force_repair_id: 264
beacon_force_repair_cost: 64
sql:
  hostname: localhost
  port: 3306
  dbname: Expensive
  username: ''
  password: ''
