name: Expensive Beacons
main: com.untamedears.rourke750.ExpensiveBeacons.ExpensiveBeaconsPlugin
version: 2.0
author: Rourke750
commands:
   eb:
      description: Base commands.
      usage: /<command>
   eb_check:
      description: Builds what the beacon will look like.
      usage: /<command> <type> <tier>
      aliases: [eb_c, eb_ch, eb_build]
   eb_refresh:
      description: Refreshes the chunks with real blocks.
      usage: /<command> <type> <tier>
      aliases: [eb_r, eb_re]